name: Release

on:
  # TODO: remove and just use schedule, once this is working
  # push:
  #   branches:
  #     - master
  schedule:
    - cron:  '23 01 01 3,6,9,12 *'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build process
        uses: devcontainers/ci@v0.3
        env:
          ELASTIC_HOST: ${{ secrets.TF_VAR_elastic_host }}
          ELASTIC_PASSWORD: ${{ secrets.TF_VAR_elastic_password }}
          ELASTIC_USERNAME: ${{ secrets.TF_VAR_elastic_username }}
        with:
          runCmd: |
            npm run gen-install-cmd
            chmod +x ./install.sh
            ./install.sh
            COVERED_STATES=OT NODE_OPTIONS=--max_old_space_size=8196 addressr-loader 
            COVERED_STATES=ACT NODE_OPTIONS=--max_old_space_size=8196 addressr-loader 
            COVERED_STATES=NT NODE_OPTIONS=--max_old_space_size=8196 addressr-loader 
            COVERED_STATES=TAS NODE_OPTIONS=--max_old_space_size=8196 addressr-loader 
            COVERED_STATES=SA NODE_OPTIONS=--max_old_space_size=8196 addressr-loader 
            COVERED_STATES=WA NODE_OPTIONS=--max_old_space_size=8196 addressr-loader 
            COVERED_STATES=QLD NODE_OPTIONS=--max_old_space_size=8196 addressr-loader 
            COVERED_STATES=VIC NODE_OPTIONS=--max_old_space_size=8196 addressr-loader 
            COVERED_STATES=NSW NODE_OPTIONS=--max_old_space_size=8196 addressr-loader 
          env: |
            ELASTIC_PORT=443
            ELASTIC_HOST
            ELASTIC_USERNAME
            ELASTIC_PASSWORD
            ELASTIC_PROTOCOL=https
            NODE_ENV=production
            ADDRESSR_ENABLE_GEO=1 
            DEBUG=error,api,express:*,swagger-tools*,test,es

