name: Release

on:
  # TODO: remove and just use schedule, once this is working
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '23 01 01 3,6,9,12 *'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-and-update:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build process
        uses: devcontainers/ci@v0.3
        env:
          ELASTIC_HOST: ${{ secrets.TF_VAR_elastic_host }}
          ELASTIC_PASSWORD: ${{ secrets.TF_VAR_elastic_password }}
          ELASTIC_USERNAME: ${{ secrets.TF_VAR_elastic_username }}
        with:
          runCmd: |
            npm run gen-install-cmd
            chmod +x ./install.sh
            ./install.sh
            COVERED_STATES=OT NODE_OPTIONS=--max_old_space_size=8196 addressr-loader 
            # npm ci --include dev
            # touch .env
            # npm run build
            # npm run start:loader:geo:OT:prod || true
            # npm run start:loader:geo:ACT:prod || true
            # npm run start:loader:geo:NT:prod || true
            # npm run start:loader:geo:TAS:prod || true
            # npm run start:loader:geo:SA:prod || true
            # npm run start:loader:geo:WA:prod || true
            # npm run start:loader:geo:QLD:prod || true
            # npm run start:loader:geo:VIC:prod || true
            # npm run start:loader:geo:NSW:prod || true
          env: |
            ELASTIC_PORT=443
            ELASTIC_HOST
            ELASTIC_USERNAME
            ELASTIC_PASSWORD
            ELASTIC_PROTOCOL=https
            NODE_ENV=production
            ADDRESSR_ENABLE_GEO=1 
            DEBUG=error,api,express:*,swagger-tools*,test,es

